

insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (55, 12, NOW(), 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'Cancelado', '5/4/2025');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (58, 12, NOW(), 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'Pendiente', '5/30/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (47, 7, NOW(), 'Donec ut dolor.', 'Cancelado', '9/9/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (54, 2, NOW(), 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Espera', '12/13/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (49, 9, NOW(), 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Cancelado', '3/19/2025');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (59, 15, NOW(), 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Completado', '2/6/2025');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (48, 14, NOW(), 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Espera', '1/10/2025');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (95, 11, NOW(), 'Suspendisse potenti.', 'Confirmado', '5/2/2025');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (81, 14, NOW(), 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'Confirmado', '9/12/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (7, 14, NOW(), 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Espera', '10/5/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (26, 5, NOW(), 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Espera', '6/2/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (70, 2, NOW(), 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'Cancelado', '9/15/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (78, 4, NOW(), 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Espera', '6/15/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (39, 3, NOW(), 'Integer ac neque.', 'Espera', '3/17/2025');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (63, 6, NOW(), 'Morbi non quam nec dui luctus rutrum.', 'Confirmado', '3/6/2025');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (78, 7, NOW(), 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Cancelado', '10/1/2024');
insert into appointments (patient_id, doctor_id, appointment_date, reason, status, created_at) values (38, 9, NOW(), 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Confirmado', '9/5/2024');
