# Stage 1: Development
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS development

WORKDIR /app

COPY ./Clinica/*.csproj ./Clinica/

RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet restore ./Clinica/Clinica.csproj

COPY ./Clinica ./Clinica

WORKDIR /app/Clinica

ENV ASPNETCORE_URLS=http://+:80 \
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true

EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--non-interactive", "--no-launch-profile"]

# Stage 2: Build (production)
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY ./Clinica/*.csproj ./Clinica/

RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet restore ./Clinica/Clinica.csproj

COPY ./Clinica ./Clinica

WORKDIR /src/Clinica

RUN dotnet publish -c Release -o /app/publish \
    --no-restore \
    /p:UseAppHost=false


# Stage 3: Production Runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS production

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:80

EXPOSE 80

ENTRYPOINT ["dotnet", "Clinica.dll"]

