name: ci-backend

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'   

      - name: Restore dependencies
        run: dotnet restore

      - name: Run formatter check
        run: |
          dotnet tool install -g dotnet-format --version 5.1.250801
          dotnet format --verify-no-changes --severity warn

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
