name: ci-backend

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          include-prerelease: true

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore backend-v1.sln

      - name: Run formatter check
        run: dotnet format backend-v1.sln --verify-no-changes --severity warn

      - name: Build
        run: dotnet build backend-v1.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test backend-v1.sln --no-build --configuration Release --verbosity normal
