name: Test Pipeline - Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_TEST }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/DockerFile
          push: true
          tags: |
            escuarch/test-software:backend-latest
            escuarch/test-software:backend-${{ github.sha }}
          cache-from: type=registry,ref=escuarch/test-software:backend-latest
          cache-to: type=inline

      - name: Deploy to Test Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 172.176.96.39
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
          script: |
            cd ~/backend-v1
            docker-compose pull backend
            docker-compose up -d
            docker image prune -f
